import { externalMockedChecklistItems } from './mocked-checklist-items';
import { externalMockedInvoices } from './mocked-invoices';
import { externalMockedTransactions } from './mocked-transaction';
import { externalMockedUsers } from './mocked-users';

import { Contract, ContractPayment } from '@models/contract';

export const externalMockedContracts: Contract[] = [
  {
    _id: '0',
    statusHistory: [],
    invoice: externalMockedInvoices[0],
    payments: [],
    receipts: [],
    expenses: [externalMockedTransactions[0], externalMockedTransactions[1]],
    status: 'Em andamento',
    version: '00',
    ISS: '0,00',
    total: '1',
    created: new Date('2021/09/14'),
    lastUpdate: new Date('2021/09/14'),
    createdExpenses: 2,
    checklist: [externalMockedChecklistItems[0]],
    managementStatus: '',
    managementNotes: '',
    locals: {
      balance: '800,00',
      value: '1.000,00',
      name: '',
      code: '',
      contractor: '',
      description: '',
      interests: '',
      role: '',
      notPaid: '718,25',
      liquid: '574,60',
      cashback: '',
      managerPicture: '',
    },
  },
  {
    _id: '1',
    statusHistory: [],
    invoice: externalMockedInvoices[1],
    payments: [
      {
        service: 'PaymentTest0',
        value: '410,00',
        team: [
          {
            user: externalMockedUsers[0],
            sector: 'Trocar',
            value: '410,00',
            percentage: '100,00',
          },
        ],
        created: new Date(),
        predictedDate: new Date(),
        lastUpdate: new Date(),
        paidDate: new Date(),
        paid: true,
      },
      {
        service: 'PaymentTest1',
        value: '410,00',
        team: [
          {
            user: externalMockedUsers[0],
            sector: 'Trocar',
            value: '205,00',
            percentage: '50,00',
          },
          {
            user: externalMockedUsers[1],
            sector: 'Trocar',
            value: '205,00',
            percentage: '50,00',
          },
        ],
        created: new Date(),
        predictedDate: new Date(),
        lastUpdate: new Date(),
        paidDate: new Date(),
        paid: true,
      },
      new ContractPayment(),
    ],
    receipts: [
      {
        value: '1.000,00',
        notaFiscal: '0,00',
        nortanPercentage: '18,00',
        description: 'TestReceipt0',
        paidDate: new Date(),
        created: new Date(),
        lastUpdate: new Date(),
        paid: true,
        ISS: '0,00',
      },
    ],
    expenses: [],
    status: 'Em andamento',
    version: '00',
    ISS: '2,00',
    total: '1',
    created: new Date('2021/09/14'),
    lastUpdate: new Date('2021/09/14'),
    createdExpenses: 2,
    checklist: [externalMockedChecklistItems[1]],
    managementStatus: '',
    managementNotes: '',
    locals: {
      balance: '0,00',
      value: '2.000,00',
      name: '',
      code: '',
      contractor: '',
      description: '',
      interests: '',
      role: '',
      notPaid: '820,00',
      liquid: '1.607,20',
      cashback: '',
      managerPicture: '',
    },
  },
  {
    _id: '2',
    statusHistory: [],
    invoice: externalMockedInvoices[2],
    payments: [],
    receipts: [
      {
        value: '965,00',
        notaFiscal: '0,00',
        nortanPercentage: '18,00',
        description: 'TestReceipt0',
        paidDate: new Date(),
        created: new Date('2022/08/01'),
        lastUpdate: new Date(),
        paid: true,
        ISS: '0,00',
      },
      {
        value: '2.327,00',
        notaFiscal: '15,00',
        nortanPercentage: '18,00',
        description: 'TestReceipt1',
        paidDate: new Date(),
        created: new Date('2023/03/05'),
        lastUpdate: new Date(),
        paid: false,
        ISS: '2,00',
      },
      {
        value: '4.367,00',
        notaFiscal: '15,00',
        nortanPercentage: '18,00',
        description: 'TestReceipt2',
        paidDate: new Date(),
        created: new Date('2023/05/05'),
        lastUpdate: new Date(),
        paid: false,
        ISS: '2,00',
      },
    ],
    expenses: [],
    status: 'Em andamento',
    version: '00',
    ISS: '2,00',
    total: '1',
    created: new Date('2021/09/14'),
    lastUpdate: new Date('2021/09/14'),
    createdExpenses: 0,
    checklist: [],
    managementStatus: '',
    managementNotes: '',
    locals: {
      balance: '0,00',
      value: '2.000,00',
      name: '',
      code: '',
      contractor: '',
      description: '',
      interests: '',
      role: '',
      notPaid: '820,00',
      liquid: '1.607,20',
      cashback: '',
      managerPicture: '',
    },
  },
];
