import { User } from '@models/user';

export const externalMockedUsers: User[] = [
  {
    _id: '0',
    company: '000000000000000000000000',
    name: 'MockedUser1',
    professionalEmail: 'mockedUser1@mocked.com',
    article: 'o',
    sectors: [],
    position: ['Associado'],
    level: 'Associado Trainee',
    expertise: [],
    AER: [],
    theme: 'default',
    active: true,
    notifications: [],
    email: 'mockedUser1@mocked.com',
    phone: '123456',
    state: 'Any',
    city: 'Any',
    document: 'Any',
    profilePicture: 'pic0@pic.com',
  },
  {
    _id: '1',
    company: '000000000000000000000000',
    name: 'MockedUser2',
    professionalEmail: 'mockedUser2@mocked.com',
    article: 'o',
    sectors: [],
    position: ['Associado'],
    level: 'Associado Trainee',
    expertise: [],
    AER: [],
    theme: 'default',
    active: true,
    notifications: [],
    email: 'mockedUser2@mocked.com',
    phone: '123456',
    state: 'Any',
    city: 'Any',
    document: 'Any',
    profilePicture: 'pic1@pic.com',
  },
  {
    _id: '2',
    company: '000000000000000000000000',
    name: 'MockedUser3',
    professionalEmail: 'mockedUser3@mocked.com',
    article: 'o',
    sectors: [],
    position: ['Associado'],
    level: 'Associado Trainee',
    expertise: [],
    AER: [],
    theme: 'default',
    active: true,
    notifications: [],
    email: 'mockedUser3@mocked.com',
    phone: '123456',
    state: 'Any',
    city: 'Any',
    document: 'Any',
    profilePicture: 'pic2@pic.com',
  },
];
