import { EXPENSE_TYPES } from '../services/config.service';
import { externalMockedUsers } from './mocked-users';

import { COST_CENTER_TYPES, Transaction } from '@models/transaction';

export const externalMockedTransactions: Transaction[] = [
  {
    _id: '0',
    contract: '0',
    author: externalMockedUsers[0],
    costCenter: externalMockedUsers[0],
    description: 'TestExpense1',
    nf: false,
    type: EXPENSE_TYPES.APORTE,
    subType: '',
    modelCostCenter: COST_CENTER_TYPES.USER,
    editionHistory: [],
    value: '1.000,00',
    paid: true,
    code: '#0',
    paidDate: new Date(),
    created: new Date(),
    lastUpdate: new Date(),
    uploadedFiles: [],
    ISS: '0,00',
    team: [
      {
        user: externalMockedUsers[0],
        value: '1.000,00',
        percentage: '100,00',
        sector: 'Trocar',
      },
    ],
  },
  {
    _id: '1',
    author: externalMockedUsers[1],
    costCenter: '1',
    modelCostCenter: COST_CENTER_TYPES.TEAM,
    description: 'TestExpense2',
    nf: false,
    type: EXPENSE_TYPES.COMISSAO,
    subType: '',
    value: '200,00',
    editionHistory: [],
    paid: true,
    code: '#1',
    paidDate: new Date(),
    created: new Date(),
    lastUpdate: new Date(),
    uploadedFiles: [],
    ISS: '0,00',
    team: [
      {
        user: externalMockedUsers[0],
        value: '120,00',
        percentage: '60,00',
        sector: 'Trocar',
      },
      {
        user: externalMockedUsers[1],
        value: '80,00',
        percentage: '40,00',
        sector: 'Trocar',
      },
    ],
  },
  {
    _id: '2',
    author: externalMockedUsers[1],
    costCenter: '1',
    modelCostCenter: COST_CENTER_TYPES.TEAM,
    contract: '1',
    description: 'TestReceipt1',
    nf: false,
    type: '',
    subType: '',
    value: '1.000,00',
    editionHistory: [],
    paid: true,
    code: '#2',
    paidDate: new Date(),
    created: new Date(),
    lastUpdate: new Date(),
    uploadedFiles: [],
    ISS: '0,00',
    team: [],
    notaFiscal: '0,00',
    companyPercentage: '18,00',
  },
  {
    _id: '3',
    author: externalMockedUsers[1],
    costCenter: '1',
    modelCostCenter: COST_CENTER_TYPES.TEAM,
    contract: '1',
    description: 'TestReceipt3',
    nf: false,
    type: '',
    subType: '',
    value: '965,00',
    editionHistory: [],
    paid: true,
    code: '#2',
    paidDate: new Date(),
    created: new Date('2022/08/01'),
    lastUpdate: new Date(),
    uploadedFiles: [],
    ISS: '0,00',
    team: [],
    notaFiscal: '0,00',
    companyPercentage: '18,00',
  },
  {
    _id: '4',
    author: externalMockedUsers[1],
    costCenter: '1',
    modelCostCenter: COST_CENTER_TYPES.TEAM,
    contract: '1',
    description: 'TestReceipt2',
    nf: false,
    type: '',
    subType: '',
    value: '2.327,00',
    editionHistory: [],
    paid: false,
    code: '#2',
    paidDate: new Date(),
    created: new Date('2023/03/05'),
    lastUpdate: new Date(),
    uploadedFiles: [],
    ISS: '2,00',
    team: [],
    notaFiscal: '15,00',
    companyPercentage: '18,00',
  },
  {
    _id: '5',
    author: externalMockedUsers[1],
    costCenter: '1',
    modelCostCenter: COST_CENTER_TYPES.TEAM,
    contract: '1',
    description: 'TestReceipt4',
    nf: false,
    type: '',
    subType: '',
    value: '4.367,00',
    editionHistory: [],
    paid: false,
    code: '#2',
    paidDate: new Date(),
    created: new Date('2023/05/05'),
    lastUpdate: new Date(),
    uploadedFiles: [],
    ISS: '2,00',
    team: [],
    notaFiscal: '15,00',
    companyPercentage: '18,00',
  },
];
